### ISSUE TITLE
setup:find_env_vars not found

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [uwiger/jobs#38]
`rebar3 xref` complains about `Warning: jobs_server:options/0 calls undefined function setup:find_env_vars/1 (Xref)`.

Looking at the code, I'm not sure we're it's supposed to come from (the function, not the warning).

**Comment by uwiger** [comment]
Sorry, I'm so used to using `setup`, it hasn't bothered me that it wasn't in the `jobs` deps. :)

**Comment by paulo-ferraz-oliveira** [comment]
Sure, but what is it? It's a generic name, so I can't easily find it 😄

**Comment by uwiger** [comment]
https://github.com/uwiger/setup

Specifically:
https://github.com/uwiger/setup/blob/master/doc/setup.md#find_env_vars-1

An example of where it's used can be seen here:
https://github.com/Feuerlabs/exodm/blob/master/lib/exodm_rpc/src/exodm_rpc.app.src#L61-L71

The `exometer_core` app supports a similar way of configuring metrics. The idea is that you can define your resources in your own app file, instead of having to maintain them in a central config.

**Comment by uwiger** [comment]
The warning is now gone, since `setup` was added to the deps

**Comment by paulo-ferraz-oliveira** [comment]
I saw that 😄 thanks.
